<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="pytest" skips="0" tests="24" time="67.732"><testcase classname="test_counter_simple" file="test_counter_simple.py" line="2" name="test_increase_counter" time="29.20067000389099"></testcase><testcase classname="test_counter_simple" file="test_counter_simple.py" line="10" name="test_increase_multiple_times" time="7.709441184997559"><failure message="AssertionError: Counter val is &quot;Invalid&quot;, expected 285
assert not True
 +  where True = &lt;bound method CounterHelper.is_invalid of &lt;fixture.counter_helper.CounterHelper object at 0x03050F30&gt;&gt;()
 +    where &lt;bound method CounterHelper.is_invalid of &lt;fixture.counter_helper.CounterHelper object at 0x03050F30&gt;&gt; = &lt;fixture.counter_helper.CounterHelper object at 0x03050F30&gt;.is_invalid
 +      where &lt;fixture.counter_helper.CounterHelper object at 0x03050F30&gt; = &lt;fixture.application.Application object at 0x03050310&gt;.counter_helper">app = &lt;fixture.application.Application object at 0x03050310&gt;

    def test_increase_multiple_times(app):
        counter_start = app.counter_helper.check_counter()
        for i in range(20):
            app.counter_helper.increase()
&gt;           assert not app.counter_helper.is_invalid(), &apos;Counter val is &quot;Invalid&quot;, expected %s&apos; % (int(counter_start) + 1)
E           AssertionError: Counter val is &quot;Invalid&quot;, expected 285
E           assert not True
E            +  where True = &lt;bound method CounterHelper.is_invalid of &lt;fixture.counter_helper.CounterHelper object at 0x03050F30&gt;&gt;()
E            +    where &lt;bound method CounterHelper.is_invalid of &lt;fixture.counter_helper.CounterHelper object at 0x03050F30&gt;&gt; = &lt;fixture.counter_helper.CounterHelper object at 0x03050F30&gt;.is_invalid
E            +      where &lt;fixture.counter_helper.CounterHelper object at 0x03050F30&gt; = &lt;fixture.application.Application object at 0x03050310&gt;.counter_helper

tests\test_counter_simple.py:15: AssertionError</failure></testcase><testcase classname="test_counter_simple" file="test_counter_simple.py" line="19" name="test_reload_page" time="2.8501627445220947"></testcase><testcase classname="test_counter_simple" file="test_counter_simple.py" line="28" name="test_counter_after_relogin" time="2.398136854171753"></testcase><testcase classname="test_list" file="test_list.py" line="5" name="test_correct_record[123]" time="0.8830504417419434"></testcase><testcase classname="test_list" file="test_list.py" line="5" name="test_correct_record[new_record]" time="1.2700726985931396"></testcase><testcase classname="test_list" file="test_list.py" line="5" name="test_correct_record[J)I]" time="1.201068639755249"></testcase><testcase classname="test_list" file="test_list.py" line="5" name="test_correct_record[?z7#BJ+a[/qpn]o&gt;9IV&gt;yZ/\ &apos;1-b@NWwXb0-Qq,]" time="1.2490713596343994"></testcase><testcase classname="test_list" file="test_list.py" line="5" name="test_correct_record[A\^)MaNe6CozMN@R1Bj#cG]" time="1.5310873985290527"></testcase><testcase classname="test_list" file="test_list.py" line="5" name="test_correct_record[388]" time="1.6230928897857666"></testcase><testcase classname="test_list" file="test_list.py" line="5" name="test_correct_record[254]" time="1.5870909690856934"></testcase><testcase classname="test_list" file="test_list.py" line="5" name="test_correct_record[22084272]" time="1.193068027496338"></testcase><testcase classname="test_list" file="test_list.py" line="5" name="test_correct_record[@,;]" time="1.1480655670166016"></testcase><testcase classname="test_list" file="test_list.py" line="5" name="test_correct_record[=[/]" time="1.7631011009216309"></testcase><testcase classname="test_list" file="test_list.py" line="5" name="test_correct_record[]{$*&gt;|]" time="1.911109209060669"></testcase><testcase classname="test_list" file="test_list.py" line="16" name="test_delete_record" time="0.6910395622253418"></testcase><testcase classname="test_list" file="test_list.py" line="28" name="test_add_max_records_num" time="1.054060459136963"></testcase><testcase classname="test_list" file="test_list.py" line="42" name="test_eleven_records" time="0.9600551128387451"></testcase><testcase classname="test_list" file="test_list.py" line="54" name="test_incorrect_record_len[]" time="1.4060804843902588"></testcase><testcase classname="test_list" file="test_list.py" line="54" name="test_incorrect_record_len[12]" time="1.6560947895050049"></testcase><testcase classname="test_list" file="test_list.py" line="54" name="test_incorrect_record_len[.]" time="0.8540487289428711"></testcase><testcase classname="test_list" file="test_list.py" line="54" name="test_incorrect_record_len[P!]" time="0.8600492477416992"></testcase><testcase classname="test_list" file="test_list.py" line="54" name="test_incorrect_record_len[JwOwCu&quot;SJ&apos;47I8g&gt;w;fU%.&quot;C93(wj~f+/elO?LNEI]" time="0.9120521545410156"></testcase><testcase classname="test_list" file="test_list.py" line="54" name="test_incorrect_record_len[F&lt;%#;xu&amp;4+h`s&lt;Fwg+6L`4&lt; `}Hi]hjBlMTN$ppD3g42mwE2e%h/I$;W^zj0%`jQ%\sLzG{%Fy/iw&apos;j7b#7TXDZ{}r~NU!|~Ue}E-%|vY|lwh}z=3,xa&amp;_3E*v*U-36o]" time="1.5990912914276123"></testcase></testsuite>